name: Build Docs
on:
  push:
    branches:
      - docs
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements_dev.txt
      - run: mkdocs gh-deploy --force
